version: "3"

services:
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    environment:
      MYSITE_SECRET_KEY: 'explorador'
      DEBUG: 1
    ports:
      - "8000:8000"
    command:
      "gunicorn --workers=2 --bind=0.0.0.0:8000 mysite.wsgi:application"
    depends_on: 
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'rutas'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'explorador'
      MYSQL_ROOT_PASSWORD: 'guardia'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    
  nginx:
    image: nginx:1.17
    container_name: ngx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app

volumes:
  my-db:
